# Generated by Django 4.2.16 on 2024-10-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SampleApp1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("extra_data", models.JSONField(default=dict)),
                ("label", models.CharField(max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
