# Generated by Django 4.2.16 on 2024-10-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jsondata_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="allowedkey",
            name="expected_values",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
