# Generated by Django 4.2.16 on 2024-10-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jsondata_manager", "0002_allowedkey_expected_values"),
    ]

    operations = [
        migrations.AddField(
            model_name="allowedkey",
            name="input_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("number", "Number"),
                    ("select", "Select"),
                    ("select_multiple", "Select Multiple"),
                    ("textarea", "Textarea"),
                ],
                default="text",
                max_length=20,
            ),
        ),
    ]
